name: Test and Publish NPM Package

on:
  push:
    branches:
      - main

jobs:
  # Job для тестов
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/src/go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('src/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run tests
        run: go test ./... -v
        working-directory: ./src

  # Job для публикации, который зависит от успешного выполнения тестов
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    needs: test  # Эта строка означает, что publish зависит от успешного выполнения тестов

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/src/go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('src/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build Go binaries
        working-directory: ./src
        run: |
          GOOS=linux GOARCH=amd64 go build -o ../npm/bin/generate-types-linux ./main.go
          GOOS=darwin GOARCH=amd64 go build -o ../npm/bin/generate-types-macos ./main.go
          GOOS=windows GOARCH=amd64 go build -o ../npm/bin/generate-types-windows.exe ./main.go

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM dependencies
        working-directory: ./npm
        run: npm install

      - name: Publish NPM Package
        working-directory: ./src
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # npm version patch
          # npm publish
